# Generated by Django 5.0 on 2023-12-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Expired', 'Expired'), ('Not Expired', 'Not Expired')], max_length=255, null=True),
        ),
    ]
