# Generated by Django 5.0 on 2023-12-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Expired', 'Expired'), ('Not Expired', 'Not Expired')], default='Not Expired', max_length=255, null=True),
        ),
    ]
