# Generated by Django 4.2.1 on 2023-09-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_rename_expiration_date_product_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
