# Generated by Django 4.2.1 on 2024-01-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='product_category', related_query_name='p_category', to='store.category'),
        ),
    ]
