# Generated by Django 4.2.1 on 2024-01-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='category', related_query_name='category', to='store.category'),
        ),
    ]
