# Generated by Django 4.2.1 on 2024-01-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_sale_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
