# Generated by Django 4.2.1 on 2024-01-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_sale_address_sale_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
