# Generated by Django 4.2.1 on 2024-01-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_sale_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
